etoro:
  api-key: dummyApiKey
  user-key: dummyUserKey
  limit-order-url: https://public-api.etoro.com/api/v1/trading/execution/demo/limit-orders
  market-order-url: http://localhost:8081/etoro/market-open-orders/by-amount
  instrument-candle-data-url: https://public-api.etoro.com/api/v1/market-data/instruments/
  order-information-url: https://public-api.etoro.com/api/v1/trading/info/demo/orders/
  portfolio-information-url: http://localhost:8081/etoro/portfolio
  url: ws://localhost:8025/ws/etoro
  simulation-date:
  simulation-portfolio-init: http://localhost:8081/etoro/init
  simulation-portfolio-value: http://localhost:8081/etoro/portfolio-value

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/strategy-simulation
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  server:
    port: 8087
