spring.application.name=HK Capital
logging.file.name=logs/hk-capital-system.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
spring.profiles.active = dev
